kind: StressChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: bookinfo-cpu-attack
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      version: v2
  mode: all
  stressors:
    cpu:
      workers: 10
      load: 100
  duration: 100s
