kind: NetworkChaos
apiVersion: chaos-mesh.org/v1alpha1
metadata:
  namespace: default
  name: bookinfo-delay
spec:
  selector:
    namespaces:
      - default
    labelSelectors:
      version: v2
  mode: all
  action: delay
  duration: 100s
  delay:
    latency: 1s
    correlation: '0'
    jitter: 0ms
